global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cost-analyzer'
    static_configs:
      - targets: ['cost-analyzer:8004']

  - job_name: 'ml-predictor'
    static_configs:
      - targets: ['ml-predictor:8005']
