apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: cloudwatch-pro
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: cloudwatch-pro
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector-service
  namespace: cloudwatch-pro
  labels:
    app: metrics-collector
spec:
  selector:
    app: metrics-collector
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: alert-manager-service
  namespace: cloudwatch-pro
  labels:
    app: alert-manager
spec:
  selector:
    app: alert-manager
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: cost-analyzer-service
  namespace: cloudwatch-pro
  labels:
    app: cost-analyzer
spec:
  selector:
    app: cost-analyzer
  ports:
    - port: 8004
      targetPort: 8004
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: ml-predictor-service
  namespace: cloudwatch-pro
  labels:
    app: ml-predictor
spec:
  selector:
    app: ml-predictor
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: cloudwatch-pro
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cloudwatch-pro
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: cloudwatch-pro
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  type: ClusterIP

